---
- name: Install Nginx
  apt: pkg=nginx
  notify:
    - Start Nginx

- name: Basic Nginx configuration
  copy: src=nginx.conf.j2 
        dest=/etc/nginx/nginx.conf 
        owner=root 
        group=root
        mode=0644
  notify:
    - Restart Nginx
