---
- name: Reload Puma
  service: name=puma
           state=reloaded

- name: Reload Nginx
  service: name=nginx
           state=reloaded

- name: Reload comedy_worker
  service: name=comedy_worker
           state=reloaded
