#!/bin/bash

set -e

cd "$(dirname "$0")/.."

rm -f bin/*

if [ "$RAILS_ENV" = "production" ]; then
  BUNDLE_ARGS="--deployment --without development --without test"
fi

bundle install --path ./vendor/bundle --standalone --clean --binstubs $BUNDLE_ARGS

export RUBY_BIN="$(ruby -e 'puts Gem.ruby')"

for binstub in bin/*; do
  load_line="$(tail -n1 "$binstub")"
  load_line="${load_line##*../../}"
  load_line="${load_line%%\'*}"
  echo "#!$RUBY_BIN" > "$binstub"
  echo 'ENV["PWD"] = File.expand_path("..", __dir__)' >> "$binstub"
  echo 'Dir.chdir(ENV["PWD"])' >> "$binstub"
  echo 'load "vendor/bundle/bundler/setup.rb"' >> "$binstub"
  echo "load \"$load_line\"" >> "$binstub"
done

for script in script/*; do
  bin="bin/${script##*/}"
  echo '#!/bin/bash' > "$bin"
  echo 'cd "$(dirname "$0")/.."' >> "$bin"
  if head -n1 "$script" | grep -q ruby; then
    echo "exec bin/ruby $script \"\$@\"" >> "$bin"
  else
    echo "exec $script \"\$@\"" >> "$bin"
  fi
  chmod +x "$bin"
done

ln -sf "$RUBY_BIN" bin/ruby

rm -rf vendor/environment vendor/lib
