#!/bin/bash

cd "$(dirname "$0")/.."

bundle install --path ./vendor/bundle --standalone --clean --binstubs --quiet

# we don't want to check in Rails' binstubs, so write them out by hand here:
cat <<RUBY > bin/rails
#!
APP_PATH = File.expand_path('../../config/application',  __FILE__)
require_relative '../config/boot'
require 'rails/commands'
RUBY

cat <<RUBY > bin/rake
#!
require_relative '../config/boot'
require 'rake'
Rake.application.run
RUBY

# rewrite shebangs to point directly to the Ruby binary instead of going through env
RUBY_PATH="$(which ruby)" perl -pi -e 's/^#!.*$/#!$ENV{RUBY_PATH}/g' bin/*

# symlink bin/ruby to the Ruby binary
ln -sf "$(which ruby)" bin/ruby
