#!/bin/bash

DEPLOY_USER="app"
DEPLOY_HOST="contestrus"

DEPLOY_TARGET="${1:-HEAD}"
SHA="$(git rev-parse "$DEPLOY_TARGET")"
ABBREV_SHA="${SHA:0:10}"

read -p "Deploying $ABBREV_SHA to production. Proceed? " -n 1
echo

if [[ ! "$REPLY" =~ ^[Yy]$ ]]; then
  exit 1
fi

ssh "$DEPLOY_USER@$DEPLOY_HOST" -- "
  set -x
  set -e
  dir_name=\"\$(date +%s)-$ABBREV_SHA\"
  mkdir \$dir_name
  cp -r current/.git \$dir_name/
  cd \$dir_name
  git fetch origin -q
  git reset --hard $SHA
  script/deploy-bootstrap
"
