#!/bin/bash

if [ "$#" = "0" ]; then
  echo "Usage: script/provision host"
  echo
  echo "Provisions a new production Contestrus server."
  exit 1
fi

FILES="script/provision-basic script/provision-production"

if [ -f "$HOME/.ssh/id_rsa.pub" ]; then
  FILES="$FILES $HOME/.ssh/id_rsa.pub"
fi

scp $FILES root@"$1":

ssh root@"$1" ./provision-production
