#!/bin/bash

DEPLOY_USER="app"
DEPLOY_HOST="contestrus"

ssh "$DEPLOY_USER"@"$DEPLOY_HOST" -- "
set -e
set -x
cd /app/current
export RAILS_ENV=production
sudo service puma stop || true
sudo service comedy_worker stop || true
bin/rake db:migrate
sudo service comedy_worker start
sudo service puma start
"
