#!/bin/bash
script/bootstrap
cp config/app_config.sample.yml config/app_config.yml

echo "Creating development database.."
bin/rake db:drop db:create db:migrate db:test:prepare db:seed competition:import[./contests/punchball]
