---
- name: Install python-pycurl for Ansible
  apt: pkg=python-pycurl
  sudo: yes

- name: Install Git
  apt: pkg=git

- name: Install build prerequisites
  apt: pkg={{ item }}
  with_items:
    - autoconf
    - build-essential

- name: Install operations tools
  apt: pkg={{ item }}
  with_items:
    - htop
    - sudo
    - vim
    - iftop
